# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alejandro Mar√≠n
description: Personal "notebook" of my learning path.
baseurl: "" # the subpath of your site, e.g. /blog
url: alejandrome.github.io # the base hostname & protocol for your site
twitter_username: AlejandroM_E
github_username:  AlejandroME
paginate: 5

permalink: "/:title"

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
